GET http://localhost:5000/users 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsIm5hbWUiOiJmYXV6aTEyIiwiZW1haWwiOiJmYXV6aTEyQGdtYWlsLmNvbSIsImlhdCI6MTczMDcwOTkyOSwiZXhwIjoxNzMwNzA5OTQ0fQ.DW4yY9wdyvNxIDJvkUH-tByLnjY-wcf-2ihwDG3DsXM

###
POST http://localhost:5000/users 
Content-Type: application/json

{
    "name" : "fauzi12",
    "email" : "fauzi12@gmail.com",
    "password" : "123",
    "confPassword": "123"
}

###
POST http://localhost:5000/login 
Content-Type: application/json

{
    "email" : "fauzi12@gmail.com",
    "password" : "123"
}

###
GET http://localhost:5000/token 

###
DELETE  http://localhost:5000/logout 